Repository tableau/TabPy, pull requests merged in 2019-04, with the labels that each got.

#233 Fix restricted evaluation bug
  tabpy-server/tabpy_server/common/endpoint_file_mgr.py
  tabpy-server/tabpy_server/handlers/evaluation_plane_handler.py
Labels: bug

#234 Add TabPy authentication
  .gitignore
  .travis.yml
  CHANGELOG
  CONTRIBUTING.md
  VERSION
  docs/TableauConfiguration.md
  docs/about.md
  docs/security.md
  docs/server-config.md
  docs/server-configurations.md
  docs/server-download.md
  docs/server-rest.md
  docs/server-startup.md
  docs/tabpy-tools.md
  misc/TabPy.yml
  startup.cmd
  startup.sh
  tabpy-server/server_tests/test_config.py
  tabpy-server/server_tests/test_endpoint_handler.py
  tabpy-server/server_tests/test_endpoints_handler.py
  tabpy-server/server_tests/test_evaluation_plane_handler.py
  tabpy-server/server_tests/test_pwd_file.py
  tabpy-server/server_tests/test_service_info_handler.py
  tabpy-server/server_tests/test_validate_credentials.py
  tabpy-server/setup.py
  tabpy-server/tabpy_server/app/ConfigParameters.py
  tabpy-server/tabpy_server/app/__init__.py
  tabpy-server/tabpy_server/app/app.py
  tabpy-server/tabpy_server/app/util.py
  tabpy-server/tabpy_server/common/default.conf
  tabpy-server/tabpy_server/common/endpoint_file_mgr.py
  tabpy-server/tabpy_server/handlers/__init__.py
  tabpy-server/tabpy_server/handlers/base_handler.py
  tabpy-server/tabpy_server/handlers/endpoint_handler.py
  tabpy-server/tabpy_server/handlers/endpoints_handler.py
  tabpy-server/tabpy_server/handlers/evaluation_plane_handler.py
  tabpy-server/tabpy_server/handlers/main_handler.py
  tabpy-server/tabpy_server/handlers/management_handler.py
  tabpy-server/tabpy_server/handlers/query_plane_handler.py
  tabpy-server/tabpy_server/handlers/service_info_handler.py
  tabpy-server/tabpy_server/handlers/status_handler.py
  tabpy-server/tabpy_server/handlers/upload_destination_handler.py
  tabpy-server/tabpy_server/handlers/util.py
  tabpy-server/tabpy_server/management/state.py
  tabpy-server/tabpy_server/management/util.py
  tabpy-server/tabpy_server/psws/callbacks.py
  tabpy-server/tabpy_server/state.ini
  tabpy-server/tabpy_server/tabpy.py
  tabpy-tools/tabpy_tools/client.py
  tabpy-tools/tabpy_tools/custom_query_object.py
  tabpy-tools/tabpy_tools/query_object.py
  tabpy-tools/tabpy_tools/rest.py
  tabpy-tools/tabpy_tools/rest_client.py
  tabpy-tools/tabpy_tools/schema.py
  tabpy-tools/tools_tests/__init__.py
  tabpy-tools/tools_tests/test_client.py
  tabpy-tools/tools_tests/test_rest.py
  tabpy-tools/tools_tests/test_rest_object.py
  utils/user_management.py
Labels: WIP, enhancement

#240 Dev tools creds
  tabpy-server/tabpy_server/handlers/base_handler.py
  tabpy-server/tabpy_server/handlers/evaluation_plane_handler.py
  tabpy-tools/tabpy_tools/client.py
  tabpy-tools/tabpy_tools/rest.py
  tabpy-tools/tabpy_tools/rest_client.py
  tabpy-tools/tools_tests/test_rest.py
Labels: enhancement

#252 weren't setting the path properly for the optional config parameter
  startup.cmd
  tabpy-server/server_tests/test_config.py
  tabpy-server/server_tests/test_pwd_file.py
  tabpy-server/tabpy_server/app/app.py
Labels: bug

#258 v0.4
  .gitignore
  CHANGELOG
  CONTRIBUTING.md
  VERSION
  docs/server-config.md
  docs/tabpy-tools.md
  startup.cmd
  tabpy-server/server_tests/test_config.py
  tabpy-server/server_tests/test_evaluation_plane_handler.py
  tabpy-server/server_tests/test_pwd_file.py
  tabpy-server/server_tests/test_service_info_handler.py
  tabpy-server/setup.py
  tabpy-server/tabpy_server/app/app.py
  tabpy-server/tabpy_server/app/util.py
  tabpy-server/tabpy_server/common/messages.py
  tabpy-server/tabpy_server/handlers/base_handler.py
  tabpy-server/tabpy_server/handlers/endpoint_handler.py
  tabpy-server/tabpy_server/handlers/endpoints_handler.py
  tabpy-server/tabpy_server/handlers/evaluation_plane_handler.py
  tabpy-server/tabpy_server/handlers/query_plane_handler.py
  tabpy-server/tabpy_server/handlers/service_info_handler.py
  tabpy-server/tabpy_server/handlers/status_handler.py
  tabpy-server/tabpy_server/management/state.py
  tabpy-tools/tabpy_tools/client.py
  tabpy-tools/tabpy_tools/rest.py
  tabpy-tools/tabpy_tools/rest_client.py
  tabpy-tools/tools_tests/test_client.py
  tabpy-tools/tools_tests/test_rest.py
Labels: enhancement

#263 Dev log user
  .gitignore
  .vscode/settings.json
  docs/server-config.md
  tabpy-server/server_tests/test_config.py
  tabpy-server/server_tests/test_evaluation_plane_handler.py
  tabpy-server/server_tests/test_service_info_handler.py
  tabpy-server/server_tests/test_validate_credentials.py
  tabpy-server/tabpy_server/app/ConfigParameters.py
  tabpy-server/tabpy_server/app/SettingsParameters.py
  tabpy-server/tabpy_server/app/app.py
  tabpy-server/tabpy_server/common/default.conf
  tabpy-server/tabpy_server/common/endpoint_file_mgr.py
  tabpy-server/tabpy_server/handlers/__init__.py
  tabpy-server/tabpy_server/handlers/base_handler.py
  tabpy-server/tabpy_server/handlers/endpoint_handler.py
  tabpy-server/tabpy_server/handlers/endpoints_handler.py
  tabpy-server/tabpy_server/handlers/evaluation_plane_handler.py
  tabpy-server/tabpy_server/handlers/management_handler.py
  tabpy-server/tabpy_server/handlers/query_plane_handler.py
  tabpy-server/tabpy_server/handlers/service_info_handler.py
  tabpy-server/tabpy_server/handlers/status_handler.py
  tabpy-server/tabpy_server/handlers/upload_destination_handler.py
  tabpy-server/tabpy_server/handlers/util.py
  tabpy-server/tabpy_server/management/state.py
  tabpy-server/tabpy_server/management/util.py
  tabpy-server/tabpy_server/psws/callbacks.py
  tabpy-tools/tabpy_tools/rest.py
  tabpy-tools/tools_tests/test_rest.py
Labels: enhancement

#268 Build is broken.
  .travis.yml
  startup.sh
  tabpy-server/setup.py
Labels: bug

#269 Add CI integration tests
  .travis.yml
  .vscode/launch.json
  .vscode/settings.json
  CHANGELOG
  CONTRIBUTING.md
  docs/api-v1.md
  docs/server-config.md
  docs/server-rest.md
  startup.cmd
  startup.sh
  tabpy-server/tabpy_server/app/app.py
  tabpy-server/tabpy_server/handlers/base_handler.py
  tests/integration/integ_test_base.py
  tests/integration/resources/2019_04_24_to_3018_08_25.crt
  tests/integration/resources/2019_04_24_to_3018_08_25.key
  tests/integration/resources/pwdfile.txt
  tests/integration/test_auth.py
  tests/integration/test_url.py
  tests/integration/test_url_ssl.py
  tests/runtests.py
  tests/unit/server_tests/__init__.py
  tests/unit/server_tests/resources/expired.crt
  tests/unit/server_tests/resources/future.crt
  tests/unit/server_tests/resources/valid.crt
  tests/unit/server_tests/test_config.py
  tests/unit/server_tests/test_endpoint_handler.py
  tests/unit/server_tests/test_endpoints_handler.py
  tests/unit/server_tests/test_evaluation_plane_handler.py
  tests/unit/server_tests/test_pwd_file.py
  tests/unit/server_tests/test_service_info_handler.py
  tests/unit/tools_tests/__init__.py
  tests/unit/tools_tests/test_client.py
  tests/unit/tools_tests/test_rest.py
  tests/unit/tools_tests/test_rest_object.py
  utils/set_env.cmd
  utils/set_env.sh
  utils/user_management.py
Labels: enhancement

#274 Update documentation with more details for auth
  CHANGELOG
  docs/server-config.md
  misc/TabPy.yml
Labels: documentation

#275 v0.4.1
  .gitignore
  .travis.yml
  .vscode/launch.json
  .vscode/settings.json
  CHANGELOG
  CONTRIBUTING.md
  VERSION
  docs/api-v1.md
  docs/server-config.md
  docs/server-rest.md
  misc/TabPy.yml
  startup.cmd
  startup.sh
  tabpy-server/server_tests/test_validate_credentials.py
  tabpy-server/tabpy_server/app/ConfigParameters.py
  tabpy-server/tabpy_server/app/SettingsParameters.py
  tabpy-server/tabpy_server/app/app.py
  tabpy-server/tabpy_server/common/default.conf
  tabpy-server/tabpy_server/common/endpoint_file_mgr.py
  tabpy-server/tabpy_server/handlers/__init__.py
  tabpy-server/tabpy_server/handlers/base_handler.py
  tabpy-server/tabpy_server/handlers/endpoint_handler.py
  tabpy-server/tabpy_server/handlers/endpoints_handler.py
  tabpy-server/tabpy_server/handlers/evaluation_plane_handler.py
  tabpy-server/tabpy_server/handlers/management_handler.py
  tabpy-server/tabpy_server/handlers/query_plane_handler.py
  tabpy-server/tabpy_server/handlers/service_info_handler.py
  tabpy-server/tabpy_server/handlers/status_handler.py
  tabpy-server/tabpy_server/handlers/upload_destination_handler.py
  tabpy-server/tabpy_server/handlers/util.py
  tabpy-server/tabpy_server/management/state.py
  tabpy-server/tabpy_server/management/util.py
  tabpy-server/tabpy_server/psws/callbacks.py
  tabpy-tools/tabpy_tools/rest.py
  tests/integration/integ_test_base.py
  tests/integration/resources/2019_04_24_to_3018_08_25.crt
  tests/integration/resources/2019_04_24_to_3018_08_25.key
  tests/integration/resources/pwdfile.txt
  tests/integration/test_auth.py
  tests/integration/test_url.py
  tests/integration/test_url_ssl.py
  tests/runtests.py
  tests/unit/server_tests/__init__.py
  tests/unit/server_tests/resources/expired.crt
  tests/unit/server_tests/resources/future.crt
  tests/unit/server_tests/resources/valid.crt
  tests/unit/server_tests/test_config.py
  tests/unit/server_tests/test_endpoint_handler.py
  tests/unit/server_tests/test_endpoints_handler.py
  tests/unit/server_tests/test_evaluation_plane_handler.py
  tests/unit/server_tests/test_pwd_file.py
  tests/unit/server_tests/test_service_info_handler.py
  tests/unit/tools_tests/__init__.py
  tests/unit/tools_tests/test_client.py
  tests/unit/tools_tests/test_rest.py
  tests/unit/tools_tests/test_rest_object.py
  utils/set_env.cmd
  utils/set_env.sh
  utils/user_management.py
Labels: documentation, enhancement
