Repository tableau/TabPy, pull requests merged in 2019-02, with the labels that each got.

#175 Dev pwd file
  .gitignore
  startup.cmd
  startup.sh
  tabpy-server/server_tests/__init__.py
  tabpy-server/server_tests/test_config.py
  tabpy-server/tabpy.py
  tabpy-server/tabpy_server/app/ConfigParameters.py
  tabpy-server/tabpy_server/app/__init__.py
  tabpy-server/tabpy_server/app/app.py
  tabpy-server/tabpy_server/app/util.py
  tabpy-server/tabpy_server/common/default.conf
  tabpy-server/tabpy_server/common/endpoint_file_mgr.py
  tabpy-server/tabpy_server/handlers/base_handler.py
  tabpy-server/tabpy_server/handlers/endpoint_handler.py
  tabpy-server/tabpy_server/handlers/endpoints_handler.py
  tabpy-server/tabpy_server/handlers/evaluation_plane_handler.py
  tabpy-server/tabpy_server/handlers/main_handler.py
  tabpy-server/tabpy_server/handlers/management_handler.py
  tabpy-server/tabpy_server/handlers/query_plane_handler.py
  tabpy-server/tabpy_server/handlers/service_info_handler.py
  tabpy-server/tabpy_server/handlers/status_handler.py
  tabpy-server/tabpy_server/handlers/upload_destination_handler.py
  tabpy-server/tabpy_server/management/state.py
  tabpy-server/tabpy_server/management/util.py
  tabpy-server/tabpy_server/psws/callbacks.py
  tabpy-server/tabpy_server/state.ini
  tabpy-server/tabpy_server/tabpy.py
  tabpy-tools/client_tests/__init__.py
  tabpy-tools/client_tests/test_client.py
Labels: WIP

#177 Bugfix: Startup scripts should fail when Python isn't in path.
  startup.cmd
  startup.sh
Labels: bug

#188 Remove unused verify_certificate parameter in Client and session
  tabpy-tools/client_tests/test_client.py
  tabpy-tools/tabpy_tools/client.py
  tabpy-tools/tabpy_tools/rest.py
Labels: bug, enhancement

#192 Dev validate creds
  CONTRIBUTING.md
  README.md
  tabpy-server/server_tests/test_config.py
  tabpy-server/server_tests/test_pwd_file.py
  tabpy-server/server_tests/test_validate_credentials.py
  tabpy-server/tabpy_server/app/app.py
  tabpy-server/tabpy_server/handlers/__init__.py
  tabpy-server/tabpy_server/handlers/util.py
Labels: WIP, enhancement
